export {
  registerUser,
  loginUser,
  verifyEmail,
  forgotPassword,
  resetPassword,
  getCurrentUser,
  getOrders,
  getOrderById,
  updateProfile,
  getAddresses,
  addAddress,
  updateAddress,
  deleteAddress,
} from './api.js'
